version: '3.8'

services:
  backend:
    build: 
      context: ./src/backend
      dockerfile: ../../Dockerfile.backend
    volumes:
      - ./src/backend:/app
      - ./src/backend/dist:/app/dist
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
      dockerfile: ../../Dockerfile.frontend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: